"""Skills indexer that generates structured JSON indexes and markdown documentation.

This module takes scanned skill metadata and produces:
- skills-index.json: A structured JSON index of all skills
- SKILLS_INDEX.md: A human-readable markdown index

It also provides search functionality over the generated index.
"""

import json
import os
from datetime import datetime, timezone
from typing import Any


def generate_index(skills: list[dict], output_dir: str) -> None:
    """Generate a skills index in both JSON and Markdown formats.

    Creates output_dir if it doesn't exist, then writes:
    - skills-index.json: structured JSON index with metadata
    - SKILLS_INDEX.md: human-readable markdown table and category listing

    Args:
        skills: List of skill metadata dicts. Each should contain at minimum:
            id, name, description, keywords, category, path, version, author.
        output_dir: Directory path where index files will be written.
    """
    os.makedirs(output_dir, exist_ok=True)

    now = datetime.now(timezone.utc).isoformat()
    categories = sorted(set(skill.get("category", "uncategorized") for skill in skills))

    # Build JSON index
    index_skills = []
    for skill in skills:
        index_skills.append({
            "id": skill.get("id", ""),
            "name": skill.get("name", ""),
            "description": skill.get("description", ""),
            "keywords": skill.get("keywords", []),
            "category": skill.get("category", "uncategorized"),
            "path": skill.get("path", ""),
            "version": skill.get("version", "1.0"),
            "author": skill.get("author", "unknown"),
        })

    index_data = {
        "version": "1.0",
        "generated": now,
        "total_skills": len(skills),
        "categories": categories,
        "skills": index_skills,
    }

    # Write JSON index
    json_path = os.path.join(output_dir, "skills-index.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(index_data, f, indent=2, ensure_ascii=False)

    # Write Markdown index
    md_path = os.path.join(output_dir, "SKILLS_INDEX.md")
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    md_content = _build_markdown_index(index_skills, categories, date_str)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)


def _build_markdown_index(skills: list[dict], categories: list[str], date_str: str) -> str:
    """Build the markdown index content.

    Args:
        skills: List of normalized skill dicts.
        categories: Sorted list of unique categories.
        date_str: Date string for the generated header.

    Returns:
        Complete markdown string for SKILLS_INDEX.md.
    """
    lines: list[str] = []

    # Header
    lines.append("# Skills Index")
    lines.append("")
    lines.append(f"> Generated by [skillify](https://github.com/raunakkathuria/skillify) on {date_str}")
    lines.append(f"> Total: {len(skills)} skills across {len(categories)} categories")
    lines.append("")

    # Table of Contents
    lines.append("## Table of Contents")
    lines.append("")
    lines.append("| # | Skill | Description | Category | Keywords |")
    lines.append("|---|-------|-------------|----------|----------|")

    for i, skill in enumerate(skills, start=1):
        name = skill.get("name", "")
        path = skill.get("path", "")
        desc = skill.get("description", "")
        category = skill.get("category", "uncategorized")
        keywords = ", ".join(skill.get("keywords", []))
        lines.append(f"| {i} | [{name}]({path}) | {desc} | {category} | {keywords} |")

    lines.append("")

    # By Category
    lines.append("## By Category")
    lines.append("")

    # Group skills by category
    skills_by_category: dict[str, list[dict]] = {}
    for skill in skills:
        cat = skill.get("category", "uncategorized")
        skills_by_category.setdefault(cat, []).append(skill)

    for category in categories:
        lines.append(f"### {category}")
        for skill in skills_by_category.get(category, []):
            name = skill.get("name", "")
            desc = skill.get("description", "")
            lines.append(f"- **{name}** — {desc}")
        lines.append("")

    return "\n".join(lines)


def search_index(index_path: str, query: str) -> list[dict]:
    """Search the skills index for skills matching a query.

    Loads the skills-index.json file and searches against name, description,
    keywords, and category fields. Results are sorted by relevance, where
    relevance is measured by the number of fields that match the query.

    Args:
        index_path: Path to the skills-index.json file.
        query: Search query string. Case-insensitive matching is used.

    Returns:
        List of matching skill dicts sorted by relevance (most relevant first).
        Each dict includes all skill fields plus a '_relevance' score.
    """
    with open(index_path, "r", encoding="utf-8") as f:
        index_data = json.load(f)

    skills = index_data.get("skills", [])
    query_lower = query.lower().strip()

    if not query_lower:
        return []

    results: list[dict] = []

    for skill in skills:
        relevance = _calculate_relevance(skill, query_lower)
        if relevance > 0:
            result = dict(skill)
            result["_relevance"] = relevance
            results.append(result)

    # Sort by relevance descending
    results.sort(key=lambda x: x["_relevance"], reverse=True)

    return results


def _calculate_relevance(skill: dict, query_lower: str) -> int:
    """Calculate a relevance score for a skill against a query.

    Checks name, description, keywords, and category fields for matches.
    Each matching field adds 1 to the score.

    Args:
        skill: Skill metadata dict.
        query_lower: Lowercased query string.

    Returns:
        Integer relevance score (0 means no match).
    """
    score = 0

    # Check name
    name = skill.get("name", "").lower()
    if query_lower in name:
        score += 1

    # Check description
    description = skill.get("description", "").lower()
    if query_lower in description:
        score += 1

    # Check keywords
    keywords = skill.get("keywords", [])
    for kw in keywords:
        if query_lower in kw.lower():
            score += 1
            break  # Only count keywords field once

    # Check category
    category = skill.get("category", "").lower()
    if query_lower in category:
        score += 1

    return score
