"""Skills indexer that generates structured JSON indexes and markdown documentation.

This module takes scanned skill metadata and produces:
- skills-index.json: A structured JSON index of all skills
- SKILLS_INDEX.md: A human-readable markdown index

It also provides search functionality over the generated index.
"""

import json
import os
from datetime import datetime, timezone

from .scanner import tokenize


def generate_index(skills: list[dict], output_dir: str, root: str = "") -> None:
    """Generate a skills index in both JSON and Markdown formats.

    Creates output_dir if it doesn't exist, then writes:
    - skills-index.json: structured JSON index with metadata
    - SKILLS_INDEX.md: human-readable markdown table and category listing

    Args:
        skills: List of skill metadata dicts. Each should contain at minimum:
            id, name, description, keywords, category, path, version, author.
        output_dir: Directory path where index files will be written.
        root: The scanned root directory. Recorded in the JSON so consumers can
            resolve the relative 'path' of each skill.
    """
    os.makedirs(output_dir, exist_ok=True)

    now = datetime.now(timezone.utc).isoformat()
    categories = sorted(set(skill.get("category", "uncategorized") for skill in skills))

    # Build JSON index
    index_skills = []
    for skill in skills:
        index_skills.append({
            "id": skill.get("id", ""),
            "name": skill.get("name", ""),
            "description": skill.get("description", ""),
            "keywords": skill.get("keywords", []),
            "category": skill.get("category", "uncategorized"),
            "path": skill.get("path", ""),
            "version": skill.get("version", "1.0"),
            "author": skill.get("author", "unknown"),
        })

    index_data = {
        "version": "1.0",
        "generated": now,
        "root": os.path.abspath(root) if root else "",
        "total_skills": len(skills),
        "categories": categories,
        "skills": index_skills,
    }

    # Write JSON index
    json_path = os.path.join(output_dir, "skills-index.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(index_data, f, indent=2, ensure_ascii=False)

    # Write Markdown index
    md_path = os.path.join(output_dir, "SKILLS_INDEX.md")
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    md_content = _build_markdown_index(index_skills, categories, date_str)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)


def _build_markdown_index(skills: list[dict], categories: list[str], date_str: str) -> str:
    """Build the markdown index content.

    Args:
        skills: List of normalized skill dicts.
        categories: Sorted list of unique categories.
        date_str: Date string for the generated header.

    Returns:
        Complete markdown string for SKILLS_INDEX.md.
    """
    lines: list[str] = []

    # Header
    lines.append("# Skills Index")
    lines.append("")
    lines.append(f"> Generated by [skillify](https://github.com/raunakkathuria/skillify) on {date_str}")
    lines.append(f"> Total: {len(skills)} skills across {len(categories)} categories")
    lines.append("")

    # Table of Contents
    lines.append("## Table of Contents")
    lines.append("")
    lines.append("| # | Skill | Description | Category | Keywords |")
    lines.append("|---|-------|-------------|----------|----------|")

    for i, skill in enumerate(skills, start=1):
        name = skill.get("name", "")
        path = skill.get("path", "")
        desc = skill.get("description", "")
        category = skill.get("category", "uncategorized")
        keywords = ", ".join(skill.get("keywords", []))
        lines.append(f"| {i} | [{name}]({path}) | {desc} | {category} | {keywords} |")

    lines.append("")

    # By Category
    lines.append("## By Category")
    lines.append("")

    # Group skills by category
    skills_by_category: dict[str, list[dict]] = {}
    for skill in skills:
        cat = skill.get("category", "uncategorized")
        skills_by_category.setdefault(cat, []).append(skill)

    for category in categories:
        lines.append(f"### {category}")
        for skill in skills_by_category.get(category, []):
            name = skill.get("name", "")
            desc = skill.get("description", "")
            lines.append(f"- **{name}** — {desc}")
        lines.append("")

    return "\n".join(lines)


# Per-field weight applied to each matching query token. A skill whose *name*
# matches the query is a far stronger signal than one that merely mentions the
# word somewhere in its description.
_FIELD_WEIGHTS: dict[str, int] = {
    "name": 5,
    "keywords": 3,
    "category": 2,
    "description": 1,
}


def search_skills(skills: list[dict], query: str, limit: int = 10) -> list[dict]:
    """Rank skills against a query by weighted token overlap.

    Scoring is deliberately simple: tokenize the query, then for each field add
    the field's weight once per distinct query token it contains, plus a bonus
    when the whole query appears verbatim. No IDF, no corpus statistics.

    Tokenized matching is what lets a sentence-shaped query work. A literal
    substring match of the full query string finds nothing for anything an agent
    would realistically ask, since it only matches when the whole phrase appears
    verbatim in a single field.

    Args:
        skills: Skill metadata dicts to rank.
        query: Search query. Case-insensitive.
        limit: Maximum number of results to return.

    Returns:
        Matching skills sorted by relevance (most relevant first), truncated to
        `limit`. Each result is a copy with a '_relevance' score added.
    """
    phrase = query.lower().strip()
    query_tokens = set(tokenize(query))

    if not phrase:
        return []

    results: list[dict] = []
    for skill in skills:
        relevance = _calculate_relevance(skill, query_tokens, phrase)
        if relevance > 0:
            results.append({**skill, "_relevance": relevance})

    # Name as tiebreaker keeps ordering stable for equally-scored skills.
    results.sort(key=lambda s: (-s["_relevance"], s.get("name", "").lower()))
    return results[:limit]


def search_index(index_path: str, query: str, limit: int = 10) -> list[dict]:
    """Search a skills-index.json file. Thin wrapper over `search_skills`.

    Args:
        index_path: Path to the skills-index.json file.
        query: Search query string.
        limit: Maximum number of results to return.

    Returns:
        List of matching skill dicts sorted by relevance.
    """
    with open(index_path, "r", encoding="utf-8") as f:
        index_data = json.load(f)

    return search_skills(index_data.get("skills", []), query, limit)


def _calculate_relevance(skill: dict, query_tokens: set[str], phrase: str) -> int:
    """Score one skill against a tokenized query.

    Args:
        skill: Skill metadata dict.
        query_tokens: Distinct content tokens from the query.
        phrase: The full lowercased query, for the verbatim-match bonus.

    Returns:
        Relevance score (0 means no match).
    """
    fields = {
        # id is folded into name: it is the slug of the name, so an agent that
        # half-remembers an id still matches.
        "name": f'{skill.get("name", "")} {skill.get("id", "")}',
        "keywords": " ".join(skill.get("keywords", [])),
        "category": skill.get("category", ""),
        "description": skill.get("description", ""),
    }

    score = 0
    for field, weight in _FIELD_WEIGHTS.items():
        text = fields[field]
        if not text:
            continue
        score += weight * len(query_tokens & set(tokenize(text)))
        if phrase in text.lower():
            score += weight

    return score
